name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dock_integ

    steps:
    - name: Build the image
    - uses: actions/checkout@v4
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Login to Docker
    - uses: docker/login-action@v3.4.0
      with:
         username: ${{ secrets.DCKR_USR }}
         password: ${{ secrets.DCKR_PAT }}
    
